### ISSUE TITLE
Unable to open a shell on cluster's nodes

### ISSUE THREAD

**Issue by JulesPichon84** [lensapp/lens#8182]
**Describe the bug**

When I try to open a shell on one of the nodes in my cluster, the shell cannot connect to the node even though I am able to execute kubectl commands with `--kubeconfig` passed in the command (on my local machine).

**Expected behavior**

I can open a shell on a node

**Screenshots**

<img width="1274" alt="Image" src="https://github.com/user-attachments/assets/f01021f3-ffbb-4a40-ba8e-3b9ade2478ad" />

**Environment (please complete the following information):**
- Lens Version: 2025.2.141554-latest
- OS: ubuntu-24.04.1-live-server

Thank you for your response !

**Comment by Tixon123** [comment]
Hello @JulesPichon84,

 Thank you for reaching out to Lens support!

 Thank you for reporting a bug. 

 We are working on your issue. Stand by for further updates.

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by panuhorsmalahti** [comment]
In Preferences -> Proxy -> Bypass Lens Internal KubeApi Proxy enabled?

**Comment by jicowan** [comment]
I am experiencing a similar issue. Initiating a node shell from the console hangs with `Connecting...` then finally says, `Error occurred: Pod creation timed outfailed to open a node shell: failed to create node pod`. If I look at the pods I can see that it started the node-shell pod on the host and if I exec into the pod, I can access the host. I am running Lens 2025.2.141554-latest. I do not have a proxy configured and I haven't needed one.

**Comment by jicowan** [comment]
On EKS, I get the following errors when using node-shell: 
```
E0306 15:03:33.491382   38090 memcache.go:265] couldn't get current server API group list: Get "https://xxxxxxxxxxxxxxxxxxxxxxxxx.gr7.us-west-2.eks.amazonaws.com/api?timeout=32s": proxyconnect tcp: dial tcp: lookup undefined: no such host
Unable to connect to the server: proxyconnect tcp: dial tcp: lookup undefined: no such host
```
This used to work on the previous version of Lens (I'm currently running 2025.2.141554-latest)

**Comment by danielgarcesruiz** [comment]
"Preferences settings" It works , Thanks

**Comment by james-hoo** [comment]
> "Preferences settings" It works , Thanks“首选项设置” 有用，谢谢

How to set it? thank you

**Comment by james-hoo** [comment]
> In Preferences -> Proxy -> Bypass Lens Internal KubeApi Proxy enabled?

Yes when I close the proxy, it works

**Comment by hq-git** [comment]
> In Preferences -> Proxy -> Bypass Lens Internal KubeApi Proxy enabled?

When I close the proxy yesterday, it works. But it doesn't work now, it's very strange. 
The only thing I can see is lens try to create node shell pod, but node shell pod is stopped very quickly.

**Comment by hq-git** [comment]
> In Preferences -> Proxy -> Bypass Lens Internal KubeApi Proxy enabled?

It works on AWS EKS 1.30 cluster, and doesn't work on EKS 1.32

**Comment by fuadimanov** [comment]
Hi, what is the downsides of disabling Lens internal proxy? Will it somehow impact my user experience on my daily usage of other functionalities?

**Comment by panuhorsmalahti** [comment]
There should be no downside.
