### PR TITLE
Use webpack instead of tsc to output extension-api.ts

### LINKED ISSUE #1262: Export `@k8slens/extensions` for writing extension unit tests
**What would you like to be added**:

Export modules of `@k8slens/extensions` (currently has only `.d.ts`) for development/testing purposes only.

**Why is this needed**:

To be able to write unit tests for extensions.

Currently test throws

```
Cannot find module '@k8slens/extensions' from 'page.tsx'

Require stack:
 page.tsx
 page.test.tsx

> 1 | import { LensRendererExtension, Component } from "@k8slens/extensions";
```

### PR DESCRIPTION
**Pull request by chenhunghan**
The original script `compile:extension-types` (introduced in https://github.com/lensapp/lens/pull/1387) which uses `tsc` to output `.d.ts` didn't (completely) resolve issue https://github.com/lensapp/lens/issues/1262, because `tsc` only transpile `.ts/tsx` to `.js`

The `require('module')/import` in `ts/tsx` are the same after transpilation. Keeping `require/import` causes https://github.com/lensapp/generator-lens-ext/pull/13 (see comments) for extension developers, when they try to import modules from `@k8slens/extensions`

The PR aims to use WebPack to solve the problem. I added a new `webpack.extensions.ts`, and used `webpack` + `ts-loader` to pack `@k8slens/extensions` as one file `extension-api.js` and output `.d.ts` just the same original `tsc`.

I tried to keep `webpack.extensions.ts` as simple as possible, so remove unnecessary settings which are in other more complicated settings such as `webpack.renderer.ts` or `webpack.main.ts`

Closes https://github.com/lensapp/lens/issues/1262

Signed-off-by: Hung-Han (Henry) Chen <1474479+chenhunghan@users.noreply.github.com>

### CODE REVIEW

File: tsconfig.extensions.json [hunk 1]
```diff
@@ -1,11 +1,9 @@
...
   "extends": "./tsconfig.json",
-  "files": [
-    "src/extensions/extension-api.ts",
-  ],
   "compilerOptions": {
     "module": "CommonJS",
-    "sourceMap": false,
-    "declaration": true
+    "declaration": true, // should output .d.ts
+    "sourceMap": true, // for use with webpack's devtool: 'inline-source-map'
```
Comment (ixrock) [inline tsconfig.extensions.json]: Comments are not valid here and editors/IDE mostly highlight with an error..

**Comment by ixrock** [comment]
Can't get what this PR fixing / improves?

**Comment by jakolehm** [comment]
> Can't get what this PR fixing / improves?

See: https://github.com/lensapp/generator-lens-ext/pull/13

File: tsconfig.extensions.json (hunk 1 above)
Comment (chenhunghan) [reply tsconfig.extensions.json]: yeah, not sure why VSCode didn't warn me :D

**Comment by ixrock** [comment]
> > Can't get what this PR fixing / improves?
> 
> See: [lensapp/generator-lens-ext#13](https://github.com/lensapp/generator-lens-ext/pull/13)

Ok, @chenhunghan please put next time relevant links in PR/issue description.

**Comment by chenhunghan** [comment]
> > > Can't get what this PR fixing / improves?
> > 
> > 
> > See: [lensapp/generator-lens-ext#13](https://github.com/lensapp/generator-lens-ext/pull/13)
> 
> Ok, @chenhunghan please put next time relevant links in PR/issue description.

sure, it's a WIP draft so I didn't put too much attention on the description.

**Comment by chenhunghan** [comment]
@jakolehm checks are passed, please take a look

File: webpack.extensions.ts [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+                        },
+                    ]
+                }
+            ]
+        },
+        resolve: {
+            extensions: ['.ts', '.tsx', '.js']
+        },
+        plugins: [
+            // In ts-loader's README they said to output a built .d.ts file,
```
Comment (jakolehm) [inline webpack.extensions.ts:76]: Should we remove these?

**Review by jakolehm — APPROVED** [review]

File: webpack.extensions.ts (hunk 2 above)
Comment (chenhunghan) [reply webpack.extensions.ts:76]: I prefer to leave it there as someone else might waste time trying...
